version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=djangoproject
      - MYSQL_USER=nram94
      - MYSQL_PASSWORD=Pablo10812$
      - MYSQL_HOST=104.154.102.101
      - MYSQL_ROOT_PASSWORD=Pablo10812$
    volumes:
      - /tmp/code/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /tmp/code/mysqld:/run/mysqld
    depends_on:
      - db

